"""Ghana Card information added

Revision ID: 185121f30468
Revises: 
Create Date: 2025-11-28 12:56:04.903098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185121f30468'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hometown_district', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hometown_region', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ghana_card', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('ghana_card')
        batch_op.drop_column('hometown_region')
        batch_op.drop_column('hometown_district')

    # ### end Alembic commands ###
